"""
Zone priority classifier for DACRO.
Rule-based weighted scoring is the authoritative classifier.
A RandomForest ML wrapper is trained on synthetic data at startup for demo credibility.
If the two disagree, rule-based always wins and the disagreement is logged.
"""

import logging
import os
import random
from typing import Dict, List

import numpy as np
from sklearn.ensemble import RandomForestClassifier

import config
from messaging.message_types import ZoneStatus

logger = logging.getLogger(__name__)

# Label order for sklearn encoding
_LABEL_ORDER = ["SAFE", "LOW", "HIGH", "CRITICAL"]
_LABEL_TO_INT = {label: i for i, label in enumerate(_LABEL_ORDER)}
_INT_TO_LABEL = {i: label for i, label in enumerate(_LABEL_ORDER)}

_MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "zone_classifier.pkl")


class ZoneClassifier:
    """
    Classifies zones into CRITICAL / HIGH / LOW / SAFE.
    Rule-based is authoritative; ML is a secondary sanity-check.
    Loads a pre-trained model from models/zone_classifier.pkl if available;
    falls back to training on synthetic data at startup otherwise.
    """

    def __init__(self) -> None:
        self.ml_model: RandomForestClassifier = RandomForestClassifier(
            n_estimators=50, random_state=42
        )
        self._load_or_train()

    def _load_or_train(self) -> None:
        """Load saved model if it exists, otherwise train from scratch."""
        if os.path.exists(_MODEL_PATH):
            try:
                import joblib
                self.ml_model = joblib.load(_MODEL_PATH)
                logger.info("ZoneClassifier loaded pre-trained model from %s", _MODEL_PATH)
                return
            except Exception as exc:
                logger.warning("ZoneClassifier failed to load saved model (%s) — retraining", exc)
        self.train_ml_model()

    # ------------------------------------------------------------------
    # Rule-based classifier (authoritative)
    # ------------------------------------------------------------------

    def classify(self, zone_status: ZoneStatus) -> str:
        """
        Return zone priority using rule-based weighted score.
        Weights from config.ZONE_SEVERITY_WEIGHTS.
        """
        weights = config.ZONE_SEVERITY_WEIGHTS
        score = (
            zone_status.severity_score * weights["severity"]
            + zone_status.population_density * weights["population"]
            + (1.0 if zone_status.has_critical_infra else 0.0) * weights["critical_infra"]
        )
        thresholds = config.PRIORITY_THRESHOLDS
        if score >= thresholds["critical"]:
            return "CRITICAL"
        if score >= thresholds["high"]:
            return "HIGH"
        if score >= thresholds["low"]:
            return "LOW"
        return "SAFE"

    def classify_all(self, zone_statuses: List[ZoneStatus]) -> Dict[str, str]:
        """
        Classify all zones; cross-checks with ML model per zone.
        Returns {zone_id: classification}.
        """
        result: Dict[str, str] = {}
        for zs in zone_statuses:
            rule_label = self.classify(zs)
            ml_label = self.classify_ml(zs)
            if rule_label != ml_label:
                logger.warning(
                    "ZoneClassifier disagreement on %s: rule=%s, ml=%s — rule-based wins",
                    zs.zone_id, rule_label, ml_label,
                )
            result[zs.zone_id] = rule_label
        return result

    # ------------------------------------------------------------------
    # ML classifier (secondary)
    # ------------------------------------------------------------------

    def train_ml_model(self, synthetic_samples: int = 500) -> None:
        """
        Generate synthetic labelled samples and train a RandomForestClassifier.
        Features: [severity_score, population_density, has_critical_infra].
        Labels: generated by the rule-based classifier for consistency.
        """
        random.seed(42)
        X, y = [], []
        for _ in range(synthetic_samples):
            severity = random.uniform(0.0, 1.0)
            pop_density = random.uniform(0.0, 1.0)
            has_infra = random.choice([0, 1])
            synthetic_zone = ZoneStatus(
                zone_id="_synthetic",
                severity_score=severity,
                classification="",
                population_density=pop_density,
                has_critical_infra=bool(has_infra),
                road_blocked=False,
                power_status=True,
            )
            label = self.classify(synthetic_zone)
            X.append([severity, pop_density, float(has_infra)])
            y.append(_LABEL_TO_INT[label])

        self.ml_model.fit(np.array(X), np.array(y))
        logger.info("ZoneClassifier ML model trained on %d synthetic samples", synthetic_samples)

    def classify_ml(self, zone_status: ZoneStatus) -> str:
        """Predict zone priority using the trained RandomForestClassifier."""
        features = np.array([[
            zone_status.severity_score,
            zone_status.population_density,
            1.0 if zone_status.has_critical_infra else 0.0,
        ]])
        prediction = self.ml_model.predict(features)[0]
        return _INT_TO_LABEL[int(prediction)]
